# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/xvp/project_1.xpr/project_1/project_1.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/xvp/project_1.xpr/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/xvp/project_1.xpr/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/xvp/project_1.xpr/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/data_memory/data_memory.mem
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/instruction_memory/instruction_memory.mem
}
read_verilog -library xil_defaultlib -sv {
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/common_pkg.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/ALU/ALU.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/ALU/ALU_control.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/add_tree_new.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/bit_extension.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/control_unit/control_unit.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/data_memory/data_memory.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/imm_generator/imm_generator.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/instruction_memory/instruction_memory.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/program_counter/program_counter.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/register_file/register_file.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/sensor_adder.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/top_risc.sv
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/components/top.sv
}
read_verilog -library xil_defaultlib {
  D:/xvp/project_1.xpr/AES/timescale.v
  D:/xvp/project_1.xpr/AES/AES_Comp_ENC.v
  D:/xvp/project_1.xpr/AES/AES_Comp_EncCore.v
  D:/xvp/project_1.xpr/AES/AES_Comp_GFinvComp.v
  D:/xvp/project_1.xpr/AES/AES_Comp_MixColumns.v
  D:/xvp/project_1.xpr/AES/AES_Comp_SboxComp.v
  D:/xvp/project_1.xpr/AES/AES_Comp_SubBytesComp.v
  D:/xvp/project_1.xpr/AES/AES_top.v
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/async_up_counter.v
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/imports/ring_oscillator/ring_oscillator.v
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/ro_sensor.v
}
read_vhdl -library xil_defaultlib {
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/add.vhd
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/ff.vhd
  D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/new/add_pipe.vhd
}
read_ip -quiet D:/xvp/project_1.xpr/project_1/project_1.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
set_property used_in_implementation false [get_files -all d:/xvp/project_1.xpr/project_1/project_1.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc]

read_ip -quiet D:/xvp/ip_repo/accelerator_1.0/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all d:/xvp/ip_repo/accelerator_1.0/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all d:/xvp/ip_repo/accelerator_1.0/vio_0/vio_0_ooc.xdc]

read_ip -quiet D:/xvp/project_1.xpr/project_1/project_1.srcs/ila_0/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/xvp/project_1.xpr/project_1/project_1.gen/ila_0/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/xvp/project_1.xpr/project_1/project_1.gen/ila_0/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/xvp/project_1.xpr/project_1/project_1.gen/ila_0/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/xvp/project_1.xpr/project_1/project_1.gen/ila_0/ip/ila_0/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/xvp/project_1.xpr/project_1/project_1.srcs/constrs_2/new/new_constraint.xdc
set_property used_in_implementation false [get_files D:/xvp/project_1.xpr/project_1/project_1.srcs/constrs_2/new/new_constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tftg256-1 -flatten_hierarchy none
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
